# Generated by Django 4.1.4 on 2023-01-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='build',
            field=models.BooleanField(default=False),
        ),
    ]
