# Generated by Django 4.1.4 on 2023-01-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
